#pragma once


Name
DirectUI::TouchSlider::BufferingProp(void)
DirectUI::TouchSlider::CancelCurrentDrag(void)
DirectUI::TouchSlider::Create(DirectUI::Element*, ulong*, DirectUI::Element**)
DirectUI::TouchSlider::EraseFeedback(void)
DirectUI::TouchSlider::FireEventOnMouseOrPointerRelease(void)
DirectUI::TouchSlider::GetBuffering(void)
DirectUI::TouchSlider::GetClassInfoPtr(void)
DirectUI::TouchSlider::GetClassInfoW(void)
DirectUI::TouchSlider::GetFillpartElement(void)
DirectUI::TouchSlider::GetIsContinuous(void)
DirectUI::TouchSlider::GetIsPressed(void)
DirectUI::TouchSlider::GetIsShowOnOffFeedback(void)
DirectUI::TouchSlider::GetIsVertical(void)
DirectUI::TouchSlider::GetMetering(void)
DirectUI::TouchSlider::GetRangeMax(void)
DirectUI::TouchSlider::GetRangeMin(void)
DirectUI::TouchSlider::GetShowTick(void)
DirectUI::TouchSlider::GetStepCount(void)
DirectUI::TouchSlider::GetThumbElement(void)
DirectUI::TouchSlider::GetThumbValue(void)
DirectUI::TouchSlider::GetTickCount(void)
DirectUI::TouchSlider::GetTrackElement(void)
DirectUI::TouchSlider::GetVisualState(void)
DirectUI::TouchSlider::Initialize(DirectUI::Element*, ulong*)
DirectUI::TouchSlider::IsContinuousProp(void)
DirectUI::TouchSlider::IsPressedProp(void)
DirectUI::TouchSlider::IsShowOnOffFeedbackProp(void)
DirectUI::TouchSlider::IsVerticalProp(void)
DirectUI::TouchSlider::MeteringProp(void)
DirectUI::TouchSlider::MouseOrPointerReleased(void)
DirectUI::TouchSlider::Register(void)
DirectUI::TouchSlider::RemoveRichDuiTooltip(void)
DirectUI::TouchSlider::SetBuffering(int)
DirectUI::TouchSlider::SetFireContinuousSliderEvent(bool)
DirectUI::TouchSlider::SetIsContinuous(bool)
DirectUI::TouchSlider::SetIsPressed(bool)
DirectUI::TouchSlider::SetIsShowOnOffFeedback(bool)
DirectUI::TouchSlider::SetIsVertical(bool)
DirectUI::TouchSlider::SetMetering(int)
DirectUI::TouchSlider::SetRangeMax(int)
DirectUI::TouchSlider::SetRangeMin(int)
DirectUI::TouchSlider::SetRangeMinAndRangeMax(int, int)
DirectUI::TouchSlider::SetRespectLanguageDirection(bool)
DirectUI::TouchSlider::SetRespondToMouseScroll(bool)
DirectUI::TouchSlider::SetShowTick(bool)
DirectUI::TouchSlider::SetStepCount(int)
DirectUI::TouchSlider::SetThumbValue(int, bool)
DirectUI::TouchSlider::SetThumbValue(int, bool, bool)
DirectUI::TouchSlider::SetTickCount(int)
DirectUI::TouchSlider::SetTooltipText(ushort const*)
DirectUI::TouchSlider::ShowTickProp(void)
DirectUI::TouchSlider::ShowTooltipOnRightForLTRBuild(void)
DirectUI::TouchSlider::SliderUpdated(void)
DirectUI::TouchSlider::ThumbPositionProp(void)
DirectUI::TouchSlider::TickCountProp(void)
DirectUI::TouchSlider::TranslateThumbPositionToThumbValue(int)
DirectUI::TouchSlider::UseFixedTooltipOffset(void)
DirectUI::TouchSlider::VisualStateProp(void)